{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "30c0903a",
   "metadata": {},
   "outputs": [],
   "source": [
    "import streamlit as st\n",
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from matplotlib.patches import Polygon\n",
    "\n",
    "# --- 1. 页面配置 ---\n",
    "st.set_page_config(page_title=\"第33题动态演示\", layout=\"wide\")\n",
    "\n",
    "# 解决中文显示问题 (Streamlit Cloud Linux环境通常没有黑体，这里使用通用字体回退方案)\n",
    "plt.rcParams['font.sans-serif'] = ['sans-serif'] \n",
    "plt.rcParams['axes.unicode_minus'] = False\n",
    "\n",
    "# --- 2. 核心数学逻辑 (保持不变) ---\n",
    "def get_triangle_CDE(c, angle_deg):\n",
    "    theta = np.radians(angle_deg)\n",
    "    xc, yc = c, c\n",
    "    xd = xc + 2 * np.cos(theta)\n",
    "    yd = yc + 2 * np.sin(theta)\n",
    "    theta_de = theta - np.pi/2\n",
    "    xe = xd + 2 * np.cos(theta_de)\n",
    "    ye = yd + 2 * np.sin(theta_de)\n",
    "    return np.array([[xc, yc], [xd, yd], [xe, ye]])\n",
    "\n",
    "def apply_n_transform(points, n, progress):\n",
    "    trans_points = points.copy()\n",
    "    if progress <= 0.5:\n",
    "        # 翻折阶段\n",
    "        t = progress / 0.5\n",
    "        trans_points[:, 1] = points[:, 1] * (1 - t) + (2 * n - points[:, 1]) * t\n",
    "    else:\n",
    "        # 平移阶段\n",
    "        trans_points[:, 1] = 2 * n - points[:, 1]\n",
    "        t = (progress - 0.5) / 0.5\n",
    "        trans_points[:, 0] = points[:, 0] + t * n\n",
    "    return trans_points\n",
    "\n",
    "def check_validity(points, c):\n",
    "    # 稍微放宽一点精度，避免浮点数误差\n",
    "    return points[1, 0] <= c + 1e-4 and points[2, 0] <= c + 1e-4\n",
    "\n",
    "def calc_c_range(angle_deg, n):\n",
    "    base_tri = get_triangle_CDE(0, angle_deg)\n",
    "    sum_D = base_tri[1, 0] + base_tri[1, 1]\n",
    "    sum_E = base_tri[2, 0] + base_tri[2, 1]\n",
    "    c1 = (n - sum_D) / 2\n",
    "    c2 = (n - sum_E) / 2\n",
    "    return min(c1, c2), max(c1, c2)\n",
    "\n",
    "# --- 3. 侧边栏控制区 ---\n",
    "st.sidebar.header(\"🕹️ 控制面板\")\n",
    "\n",
    "# 1. 变换动画\n",
    "prog = st.sidebar.slider(\"1. 变换进度 (n型变换)\", 0.0, 1.0, 0.0, 0.01)\n",
    "\n",
    "# 2. 几何参数\n",
    "st.sidebar.markdown(\"---\")\n",
    "c = st.sidebar.slider(\"2. 点C位置 (参数 c)\", -5.0, 8.0, 1.0, 0.1)\n",
    "n = st.sidebar.slider(\"3. 参数 n\", 1.0, 5.0, 3.0, 0.1)\n",
    "angle = st.sidebar.slider(\"4. 旋转角度\", 0.0, 360.0, 180.0, 5.0)\n",
    "\n",
    "# --- 4. 主绘图区 ---\n",
    "st.title(\"📐 第(3)问：n型对照变换与c的取值范围\")\n",
    "st.markdown(\"拖动左侧滑块，观察三角形的变化。\")\n",
    "\n",
    "# 创建图形\n",
    "fig, ax = plt.subplots(figsize=(8, 8))\n",
    "ax.set_aspect('equal')\n",
    "ax.set_xlim(-6, 12)\n",
    "ax.set_ylim(-6, 12)\n",
    "ax.grid(True, linestyle='--', alpha=0.4)\n",
    "\n",
    "# 绘制辅助线\n",
    "ax.plot([-10, 20], [-10, 20], 'k--', linewidth=1, label='y=x')\n",
    "ax.plot([-10, 20], [n, n], 'b-.', linewidth=1, label=f'y={n}')\n",
    "\n",
    "# 计算数据\n",
    "pts_orig = get_triangle_CDE(c, angle)\n",
    "is_valid = check_validity(pts_orig, c)\n",
    "pts_trans = apply_n_transform(pts_orig, n, prog)\n",
    "\n",
    "# 绘制三角形\n",
    "if is_valid:\n",
    "    color_orig = 'purple'\n",
    "    color_trans = 'green'\n",
    "    alpha_trans = 0.6\n",
    "    status_msg = \"✅ 满足题意 (xD≤c, xE≤c)\"\n",
    "else:\n",
    "    color_orig = 'gray'\n",
    "    color_trans = 'gray'\n",
    "    alpha_trans = 0.3\n",
    "    status_msg = \"❌ 不合题意 (存在点横坐标 > c)\"\n",
    "\n",
    "# 原三角形\n",
    "poly_orig = Polygon(pts_orig, closed=True, fill=False, edgecolor=color_orig, linestyle='--', linewidth=1)\n",
    "ax.add_patch(poly_orig)\n",
    "\n",
    "# 变换后三角形\n",
    "poly_trans = Polygon(pts_trans, closed=True, color=color_trans, alpha=alpha_trans)\n",
    "ax.add_patch(poly_trans)\n",
    "\n",
    "# 标注顶点\n",
    "offset = 0.4\n",
    "labels = ['C', 'D', 'E']\n",
    "for i, p in enumerate(pts_orig):\n",
    "    ax.text(p[0], p[1]+offset, labels[i], color=color_orig, fontsize=10, ha='center')\n",
    "\n",
    "for i, p in enumerate(pts_trans):\n",
    "    ax.text(p[0], p[1]-offset, labels[i]+\"'\", color='darkgreen' if is_valid else 'gray', fontsize=10, ha='center')\n",
    "\n",
    "# 计算和绘制 c 的范围\n",
    "c_min, c_max = calc_c_range(angle, n)\n",
    "if is_valid:\n",
    "    ax.plot([c_min, c_max], [c_min, c_max], 'r-', linewidth=4, alpha=0.5, label='c 可行范围')\n",
    "\n",
    "# 判断交点\n",
    "has_intersection = False\n",
    "if prog >= 0.99:\n",
    "    d_prime = pts_trans[1]\n",
    "    e_prime = pts_trans[2]\n",
    "    val_d = d_prime[1] - d_prime[0]\n",
    "    val_e = e_prime[1] - e_prime[0]\n",
    "    has_intersection = (val_d * val_e <= 0)\n",
    "\n",
    "# 显示图例\n",
    "ax.legend(loc='upper left')\n",
    "\n",
    "# 在 Streamlit 中显示 Matplotlib 图形\n",
    "st.pyplot(fig)\n",
    "\n",
    "# --- 5. 文字信息反馈区 ---\n",
    "col1, col2 = st.columns(2)\n",
    "with col1:\n",
    "    st.info(f\"**当前状态**: {status_msg}\")\n",
    "    \n",
    "    intersect_str = \"等待变换完成...\"\n",
    "    if prog >= 0.99:\n",
    "        intersect_str = \"🔴 相交\" if has_intersection else \"🔵 不相交\"\n",
    "    st.write(f\"**D'E' 与 y=x 关系**: {intersect_str}\")\n",
    "\n",
    "with col2:\n",
    "    st.success(f\"**c 的理论范围**: [{c_min:.2f}, {c_max:.2f}]\")\n",
    "    \n",
    "    delta = 0.05\n",
    "    if c_min - delta <= c <= c_max + delta:\n",
    "         st.write(f\"**当前 c = {c:.2f}** (在范围内 ✅)\")\n",
    "    else:\n",
    "         st.write(f\"**当前 c = {c:.2f}** (在范围外)\")"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.11"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
